[build]
  command = "npx prisma generate --schema=prisma/schema.production.prisma && npx prisma db push --schema=prisma/schema.production.prisma && node scripts/seed-production.js && npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--production=false"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  node_bundler = "esbuild"
