[build]
  command = "npx prisma generate --schema=prisma/schema.production.prisma && npx prisma db push --schema=prisma/schema.production.prisma && npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20"
